apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: demo
spec:
  selector:
    app: flask
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
